name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======
      env:
        TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
>>>>>>> e3bbd3f5e95d5c71a96ef8b884fc5472de509084
    steps:
      env:
        TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun next build
