name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Envirnment variable
        env:
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE.API.KEY }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun next build
