name: "Test"
on: [push, pull_request]

# TODO setup a firebase emulator container to run firebase tests

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Test
        run: bun wiptest
