name: "Test"
on: [push, pull_request]

jobs:
  test:
    services:
      firebase-emulator:
        image: spine3/firebase-emulator:latest
        ports:
          - 9000:9000
          - 8080:8080
          - 4000:4000
          - 9099:9099
          - 8085:8085
          - 5001:5001
          - 9199:9199
        env:
          GCP_PROJECT: asoltd-guilds
          ENABLE_UI: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Test
        run: bun wiptest
