on: [push]
name: variable substitution in json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1
    with:
      files: "secrets.json"
    env:
      apiKey: ${{ secrets.TYPESENSE_API_KEY }}
      url: https://github.com/asoltd/guilds
